kind: Service
apiVersion: v1
metadata:
  name: fleetman-webapp
spec:
  selector:
    # This defines which pods are going to be represented by this Service
    # The Service becomes a network endpoint for either other services
    # or maybe external users to connect to (eg: browser)
    app: webapp
  ports:
  - port: 80
    nodePort: 30080
    name: http
  type: NodePort


---

kind: Service
apiVersion: v1
metadata:
  name: fleetman-queue

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616

  type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  name: fleetman-position-tracker

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080

  type: ClusterIP


---

kind: Service
apiVersion: v1
metadata:
  name: fleetman-api-gateway

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080

  type: ClusterIP