kind: Service
apiVersion: v1
metadata:
  name: fleetman-webapp
spec:
  selector:
    # This defines which pods are going to be represented by this Service
    # The Service becomes a network endpoint for either other services
    # or maybe external users to connect to (eg: browser)
    app: webapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  type: NodePort


---

kind: Service
apiVersion: v1
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
  - port: 8161
    nodePort: 30010
  type: NodePort
